### ISSUE TITLE
I can't get the yandex games language

### ISSUE THREAD

**Issue by DiFo89** [Koallider/flutter_yandex_games#9]
I get the language through `YandexGames.environment.i18n.lang`, but returns an empty string.

index.html
```
<!DOCTYPE html>
<html>

<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    For more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

    This is a placeholder for base href that will be replaced by the value of
    the `--base-href` argument provided to `flutter build`.
  -->
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="angryfood">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png" />

  <title>angryfood</title>
  <link rel="manifest" href="manifest.json">
</head>

<body>
  <!--<script src="https://yandex.ru/games/sdk/v2"></script>-->
  <!--<script src="/sdk.js"></script>-->
  <script src="https://unpkg.com/@vkontakte/vk-bridge@2.5.1/dist/browser.min.js"></script>

  <script>
    vkBridge.subscribe((event) => {
      if (window.vkBridgeDartListener != null) {
        window.vkBridgeDartListener(event.detail);
      }
    });
  </script>

  <script src="main.dart.js" type="application/javascript"></script>
  <script src="flutter_bootstrap.js" async></script>
</body>

</html>
```

pubspec.yaml (my packages)
```
name: angry_food
description: "A new Flutter project."
publish_to: "none"

version: 1.0.2+11

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  go_router: ^14.2.7
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  spine_flutter: ^4.2.32
  audioplayers: ^6.4.0
  flutter_yandex_games: ^0.0.7
  flutter_bloc: ^8.1.6
  appmetrica_plugin: ^3.1.0
  flutter_launcher_icons: ^0.14.2
  yandex_mobileads: ^7.11.0
  vk_bridge: ^2.4.0
  in_app_purchase: ^3.2.1
  flutter_rustore_billing: ^7.0.1
  huawei_iap: ^6.13.0+304
  amazon_iap: ^0.2.2
  uuid: ^4.5.1
  flutter_sound: ^9.27.0
  logger: ^2.5.0
  stack_appodeal_flutter: ^3.5.0

dependency_overrides:
  audioplayers_android:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: "packages/audioplayers_android"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  image_path: "assets/images/Logo.png"
  adaptive_icon_background: "#21B5FF00"
  adaptive_icon_foreground: "assets/images/Logo.png"
  remove_alpha_ios: true
  android: true
  ios: true
  windows:
    generate: true
  web:
    generate: true
  macos:
    generate: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/config/
    - assets/sounds/
    - assets/sounds/scenesounds/
    - assets/sounds/items/
    - assets/spine/
    - assets/spine/characters/
    - assets/spine/backgrounds/
    - assets/spine/locations/
    - assets/spine/shop/
    - assets/spine/buttons/
    - assets/spine/scenes/
    - assets/spine/elements/
    - assets/spine/intro/

  fonts:
    - family: My Times New Roman
      fonts:
        - asset: assets/fonts/timesnewromanpsmt.ttf
        - asset: assets/fonts/timesnewromanps_italicmt.ttf
          style: italic
    - family: Epilepsy Sans
      fonts:
        - asset: assets/fonts/EpilepsySans.ttf

```
yandex games init
```
await YandexGames.init().then((val) {
      YandexGames.loadingApi.ready();
    });
```
